### ISSUE TITLE
usageDataPoints timestamps from Emporia

### ISSUE THREAD

**Issue by biker2000on** [jertel/vuegraf#117]
Need to pull the timestamps from the returned values from Emporia and not just assume it is the start and stop times.

**Comment by jertel** [comment]
Please elaborate or submit a PR.

**Comment by biker2000on** [comment]
Sorry, I created a fork of vuegraf that posts the data to MQTT instead of influx. That way I can pick it up via telegraf and send it to Timescale, Influx, and TDEngine all at the same time. This was supposed to be an issue for me to follow up on for the fork.

**Comment by jertel** [comment]
Ah! That makes sense now. Thanks for clarifying. :)
