### ISSUE TITLE
influx requires minimum 8 characters for password, writeup say to use 'vuegraf', but this is < 8 characters

### ISSUE THREAD

**Issue by bwmcin** [jertel/vuegraf#130]
I installed influxdb per the docker instructions provided.  Upon setting up the initial user, I entered vuegraf fro user name, but when I entered vuegraf for the password, the screen said that "Password must be at least 8 characters".  Please update accordingly.

**Comment by jertel** [comment]
It has been updated accordingly. Thanks.
