### ISSUE TITLE
Minimal Configuration doc

### ISSUE THREAD

**Issue by jbird526** [jertel/vuegraf#32]
In the doc for Minimal Configuration the "password" has a trailing comma that if used in .json, will cause container startup to fail.
{
    "influxDb": {
        "host": "my.influxdb.hostname",
        "port": 8086,
        "user": "root",
        "pass": "root",
        "database": "vue",
        "reset": false
    },
    "accounts": [
        {
            "name": "Primary Residence",
            "email": "my@email.address",
            "password": "my-emporia-password",
        }
    ]
}

**Comment by jertel** [comment]
Fixed. Thanks.
