### ISSUE TITLE
Is it possible to create a Virtual datapoint for 'Balance' 

### ISSUE THREAD

**Issue by Sjcnu-GhubAdmin** [jertel/vuegraf#62]
I'd like to have a Virtual Datapoint 'Unmonitored' or 'Balance' that is equal to '1,2,3' - Sum(all other datapoints) to account for breakers with no monitor on them.

**Comment by jertel** [comment]
I've pushed a change that will now record the Balance metrics (for vue devices) and the TotalUsage metrics (for solar devices). They will appear in Influx as:
```
<device name>-Balance
<device name>-TotalUsage
```

**Comment by Sjcnu-GhubAdmin** [comment]
Thank you! trying to do this on the influx side was.. not going well :)
