### ISSUE TITLE
issues with smart plugs after API update 8/31/21

### ISSUE THREAD

**Issue by kpnobvious** [jertel/vuegraf#73]
FYI, I am getting the following error parsing devices:
Fatal error: (<class 'TypeError'>, TypeError('Parser must be a string or character stream, not NoneType')

I updated PyEmVue already with their changes and am pretty sure it is related to the 2 smart plugs i have and this issue with PyEmVue - https://github.com/magico13/PyEmVue/issues/30

Just in case anyone else is seeing that from yesterdays changes.

**Comment by jertel** [comment]
The fix to Vuegraf was pushed earlier this morning.

**Comment by kpnobvious** [comment]
ok, i am already on pyemvue 15.0 and i didn't see any changes since then to the vuegraf source since about a week ago.

**Comment by jertel** [comment]
It sounds like you're not using the Docker image. In that case, if it continues to fail with that parse error then my best guess is that it's not using the correct version of PyEmVue.

**Comment by kpnobvious** [comment]
ok, thanks Jertel.  I'm not using the docker image, i bet python might be cached using an old version

**Comment by kpnobvious** [comment]
yup, totally my issue, i had updated pyemvue but didn't pass the upgrade cmd to pip, so it was still old.
