### ISSUE TITLE
Already Exsisiting Database

### ISSUE THREAD

**Issue by 12nick12** [jertel/vuegraf#77]
Can't use with database that already exists. I commented the createdatabase function and it worked I'm not very good at python so I'm not sure how to do the if/else logic from the json config.

**Comment by jertel** [comment]
Please see https://github.com/jertel/vuegraf/issues/11 and provide more information, such as redacted configuration and logs showing the errors.

Issues are intended for well-documented, reproducible problems. If you're looking for support use the Discussions.
