### ISSUE TITLE
User friendly names

### ISSUE THREAD

**Issue by castro145** [jertel/vuegraf#9]
Hello,
Thank a bunch for the project, I love Grafana and got the Vue2 yesterday, this is AWESOME! Quick question, I seem to be having issues adding the name that the circuit is named.

As an example, my circuit 5 name in the Vue app named "AC Downstairs", the Circuit Type is "Air Conditioner". When the vuegraf starts in docker in the log it outputs "Discovered new channel: AC Downstairs (5)". In the config I've tried setting the "Left" and the "Right" 5th device down to both the "AC Downstairs" and ""Air Conditioner" but with no luck as it always shows up as "Home-5". "Home" being the Name of the Vue monitor.

Thanks for any help you can provide.

Joe

**Comment by jertel** [comment]
In your config make sure you the name of your vue device itself, which sounds like it is _Home_ in your case. For example, if you only have one Vue device then delete the "Right" device from the config (remove the trailing comma above it as well), and then change the "Left Panel" name to be "Home".

So it would look like this:
```
            "devices": [
                {
                    "name": "Home",
                    "channels": [
                        "xxxx",
                        "xxxx",
                        "xxxx",
                        "xxxx",
                        "AC Downstairs",
                        "xxxx",
                        "xxxx",
                        "xxxx"
                    ]
                }
            ]
```
